package vista;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import vista.InicioEmp;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import controlador.ConexionBD;

public class RegistrarAdm extends javax.swing.JFrame {
    
    private void cargarIdsTiendas() {
        ConexionBD conexionBD = new ConexionBD();
        try (Connection conn = conexionBD.ConectarBaseDatos()) {
            String sql = "SELECT id_tien FROM tiendas";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            cbxIdTiendaEmpleado.removeAllItems(); // Limpiar el JComboBox antes de cargar los datos
            while (rs.next()) {
                cbxIdTiendaEmpleado.addItem(rs.getString("id_tien")); // Añadir cada ID al JComboBox
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los IDs de tiendas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarIdsUsuarios() {
    ConexionBD conexionBD = new ConexionBD();
    try (Connection conn = conexionBD.ConectarBaseDatos()) {
        String sql = "SELECT id_usu FROM usuarios WHERE rol_usu = 'emple'";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        cbxIdUsuarioEmpleado.removeAllItems(); // Limpiar el JComboBox antes de cargar los datos
        while (rs.next()) {
            cbxIdUsuarioEmpleado.addItem(rs.getString("id_usu")); // Añadir cada ID al JComboBox
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los IDs de usuarios: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    public RegistrarAdm() {
        initComponents();
        cargarIdsTiendas();
        cargarIdsUsuarios();
        this.setLocationRelativeTo(this);
        this.setTitle("Registrar empleados y usuarios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuarioEmpleado = new javax.swing.JTextField();
        btnRegistrarUsuarioEmpleado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        cbxIdTiendaEmpleado = new javax.swing.JComboBox<>();
        cbxIdUsuarioEmpleado = new javax.swing.JComboBox<>();
        btnRegistrarInformacionUsuarioEmpleado = new javax.swing.JButton();
        txtContraUsuario = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inicio/");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("Registrar");

        jLabel3.setText("Ingreso de datos de Usuarios Empleados");

        jLabel4.setText("Ingrese usuario");

        jLabel5.setText("Ingrese contraseña");

        btnRegistrarUsuarioEmpleado.setText("Registrar");
        btnRegistrarUsuarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioEmpleadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingresa nombre");

        jLabel7.setText("Ingresa apellido");

        jLabel8.setText("Elija ID de la tienda");

        jLabel9.setText("Elija el ID de usuario");

        jLabel10.setText("Ingreso de datos de Empleados");

        btnRegistrarInformacionUsuarioEmpleado.setText("Registrar");
        btnRegistrarInformacionUsuarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarInformacionUsuarioEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRegistrarInformacionUsuarioEmpleado)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel5))
                                            .addGap(98, 98, 98)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cbxIdUsuarioEmpleado, 0, 114, Short.MAX_VALUE)
                                                .addComponent(cbxIdTiendaEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtApellidoEmpleado)
                                                .addComponent(txtNombreEmpleado)
                                                .addComponent(txtContraUsuario)
                                                .addComponent(txtUsuarioEmpleado)))
                                        .addComponent(jLabel3))
                                    .addGap(38, 38, 38)
                                    .addComponent(btnRegistrarUsuarioEmpleado)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel10)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnRegistrarUsuarioEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtContraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addComponent(btnRegistrarInformacionUsuarioEmpleado)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxIdTiendaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxIdUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarInformacionUsuarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarInformacionUsuarioEmpleadoActionPerformed
      // Obtener los valores de los campos de texto y ComboBox
    String nombreUsuarioEmpleado = txtNombreEmpleado.getText();
    String apellidoUsuarioEmpleado = txtApellidoEmpleado.getText();
    String idTiendaEmpleado = (String) cbxIdTiendaEmpleado.getSelectedItem(); // ID de tienda seleccionado
    String idUsuarioEmpleado = (String) cbxIdUsuarioEmpleado.getSelectedItem(); // ID de usuario seleccionado

    // Comprobar que los campos no estén vacíos
    if (nombreUsuarioEmpleado.isEmpty() || apellidoUsuarioEmpleado.isEmpty() || idTiendaEmpleado == null || idUsuarioEmpleado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Insertar los datos en la base de datos
    ConexionBD conexionBD = new ConexionBD();
    try (Connection conn = conexionBD.ConectarBaseDatos()) {
        String sql = "INSERT INTO empleados (nom_emp, ape_emp, id_tien, id_usu) VALUES (?, ?, ?, ?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, nombreUsuarioEmpleado);
        stmt.setString(2, apellidoUsuarioEmpleado);
        stmt.setString(3, idTiendaEmpleado);
        stmt.setString(4, idUsuarioEmpleado);

        int filasInsertadas = stmt.executeUpdate();
        if (filasInsertadas > 0) {
            JOptionPane.showMessageDialog(this, "Empleado registrado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al registrar el empleado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnRegistrarInformacionUsuarioEmpleadoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    InicioEmp objInicio = new InicioEmp();
    objInicio.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnRegistrarUsuarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioEmpleadoActionPerformed
    String usuario_empleado = txtUsuarioEmpleado.getText();
    String contrasena_empleado = new String (txtContraUsuario.getText());
    
     // Validar que los campos no estén vacíos
    if (usuario_empleado.isEmpty() || contrasena_empleado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Definir la conexión y la consulta SQL
    Connection conn = null;
    Statement stmt = null;
    
     try {
             // Crear una instancia de ConexionBD y obtener la conexión
            ConexionBD conexion = new ConexionBD();
            conn = conexion.ConectarBaseDatos();  // Usar el método que ya tienes

            // Consulta SQL para insertar un nuevo usuario utilizando Statement (sin PreparedStatement)
            String sql = "INSERT INTO usuarios (nom_usu, cont_usu, rol_usu) VALUES ('" + usuario_empleado + "', '" + contrasena_empleado + "', 'emple')";

            // Crear el Statement para ejecutar la consulta
            stmt = conn.createStatement();

            // Ejecutar la consulta
            int filasAfectadas = stmt.executeUpdate(sql);

            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar los recursos
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al cerrar la conexión: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
     
    
    }//GEN-LAST:event_btnRegistrarUsuarioEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarInformacionUsuarioEmpleado;
    private javax.swing.JButton btnRegistrarUsuarioEmpleado;
    private javax.swing.JComboBox<String> cbxIdTiendaEmpleado;
    private javax.swing.JComboBox<String> cbxIdUsuarioEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JPasswordField txtContraUsuario;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
